---
- name: "Create app folder"
  file:
    path: ~/app
    state: directory

- name: "Unarchive artifact.tar.gz"
  unarchive:
    src: files/artifact.tar.gz
    dest: ~/app

- name: "Start the app"
  shell: |
    cd ~/app
    npm i
    pm2 stop default
    pm2 start main.js
